language: ruby

rvm:
  - 2.1
  - 2.2
  - 2.3.1
  - 2.4.1
  - 2.5.0
  - ruby-head

before_install:
  - gem update --system=2.7.8
script:
  - bundle exec rake test

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head

