name: linux
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 1 * *'
jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      min_version: 3.0
  build:
    needs: ruby-versions
    runs-on: ${{ matrix.os }}
    env:
      USE_RDKAFKA: 1
    strategy:
      fail-fast: false
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        os:
          - ubuntu-latest
        rdkafka_versions:
          - { min: '>= 0.6.0', max: '< 0.12.0' }
          - { min: '>= 0.12.0', max: '< 0.14.0' }
          - { min: '>= 0.14.0', max: '< 0.16.0' }
          - { min: '>= 0.16.0', max: '< 0.25.0' }
          - { min: '>= 0.25.0', max: '>= 0.25.0' }
        # rdkafka 0.25.0 supports Ruby 3.2+, so we exclude it for Ruby 3.0 and 3.1
        exclude:
          - ruby: head
          - ruby: '3.1'
            rdkafka_versions: { min: '>= 0.25.0', max: '>= 0.25.0' }
          - ruby: '3.0'
            rdkafka_versions: { min: '>= 0.25.0', max: '>= 0.25.0' }
        # rdkafka 0.15.2 is the last version which supports Ruby 2.7
        include:
          - ruby: '2.7'
            os: ubuntu-latest
            rdkafka_versions: { min: '>= 0.6.0', max: '< 0.12.0' }
          - ruby: '2.7'
            os: ubuntu-latest
            rdkafka_versions: { min: '>= 0.12.0', max: '= 0.15.2' }
    name: Ruby ${{ matrix.ruby }} unit testing on ${{ matrix.os }} with rdkafka gem version (min ${{ matrix.rdkafka_versions.min }} max ${{ matrix.rdkafka_versions.max }})
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ruby/setup-ruby@4dc28cf14d77b0afa6832d9765ac422dbf0dfedd # v1.298.0
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install confluent-kafka
      run: |
        sudo apt install -V -y gnupg2 wget
        wget https://packages.confluent.io/deb/6.0/archive.key
        sudo gpg2 --homedir /tmp --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/confluent-archive-keyring.gpg --import archive.key
        sudo chmod 644 /usr/share/keyrings/confluent-archive-keyring.gpg
        sudo sh -c 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/confluent-archive-keyring.gpg] https://packages.confluent.io/deb/6.0 stable main" > /etc/apt/sources.list.d/confluent.list'
        sudo apt update
        sudo apt install -y confluent-community-2.13 openjdk-11-jre netcat-openbsd
    - name: unit testing
      env:
        CI: true
        RDKAFKA_VERSION_MIN_RANGE: ${{ matrix.rdkafka_versions.min }}
        RDKAFKA_VERSION_MAX_RANGE: ${{ matrix.rdkafka_versions.max }}
      run: |
        sudo ./ci/prepare-kafka-server.sh
        bundle install --jobs 4 --retry 3
        bundle exec rake test
